    name: Secretlint
    on: [push, pull_request]
    permissions:
      contents: read
    jobs:
      test:
        name: "Secretlint"
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Build Secretlint Docker image
            id: build_image
            run: docker build -t secretlint-scanner ./.github

          - name: Run Secretlint scanner
            # 运行我们刚刚构建的 Docker 镜像
            # -v "${{ github.workspace }}:/scan-target" 将仓库代码挂载到容器的 /scan-target 目录
            # 最后指定扫描目标为 /scan-target
            run: docker run --rm -v "${{ github.workspace }}:/scan-target" secretlint-scanner "/scan-target/**/*"
    
      